on:
  issues:
    types:
      - labeled
      - edited

jobs:
  issue_to_markdown_ko:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: eunjae-lee/issue-to-markdown@v0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: 'publish_ko'
          dest: 'posts/ko'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update contents'
  issue_to_markdown_en:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: eunjae-lee/issue-to-markdown@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: 'publish_en'
          dest: 'posts/en'
          inject_created_at: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update contents'
  issue_to_markdown_tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: eunjae-lee/issue-to-markdown@v0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: 'publish_tweet'
          dest: 'posts/tweet'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update contents'
